export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";//Action type này sẽ được sử dụng để lấy tất cả sản phẩm từ API.
export const TOGGLE_AUTH = "TOGGLE_AUTH";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn form đăng nhập.
export const GET_ALL_NXB = "GET_ALL_NXB";
export const GET_ALL_POST = "GET_ALL_POST";
export const GET_PRODUCT_BY_PAGE = "GET_PRODUCT_BY_PAGE";//Action type này sẽ được sử dụng để lấy sản phẩm theo trang từ API.
export const IS_LOADING_BOOKSTORE = "IS_LOADING_BOOKSTORE";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy sản phẩm từ API.
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";//Action type này sẽ được sử dụng để lấy một sản phẩm từ API.
export const IS_LOADING_DETAIL_P = "IS_LOADING_DETAIL_P";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy một sản phẩm từ API.
export const ADD_REVIEW_PRODUCT = "ADD_REVIEW_PRODUCT";//Action type này sẽ được sử dụng để thêm đánh giá sản phẩm.
export const SET_USER = "SET_USER";//Action type này sẽ được sử dụng để lưu thông tin người dùng vào localStorage.
export const IS_LOADING_ALL = 'IS_LOADING_ALL';//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy tất cả sản phẩm từ API.
export const GET_ONE_POST = 'GET_ONE_POST';//Action type này sẽ được sử dụng để lấy một bài viết từ API.
export const ADD_CMT_POST = "ADD_CMT_POST";//Action type này sẽ được sử dụng để thêm bình luận vào bài viết.
export const GET_COMMENT = "GET_COMMENT";//Action type này sẽ được sử dụng để lấy tất cả bình luận từ API.
export const REPLY_COMMENT = "REPLY_COMMENT";//Action type này sẽ được sử dụng để trả lời bình luận.
export const IS_LOADING_CMT = "IS_LOADING_CMT";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy bình luận từ API.
export const GET_ALL_TYPE_PRODUCT = "GET_ALL_TYPE_PRODUCT";//Action type này sẽ được sử dụng để lấy tất cả loại sản phẩm từ API.
export const GET_POST_BY_PAGE = "GET_POST_BY_PAGE";//Action type này sẽ được sử dụng để lấy bài viết theo trang từ API.
export const IS_LOADING_DETAIL_B = "IS_LOADING_DETAIL_B";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy một bài viết từ API.
export const GET_PRODUCT_SEARCH_FIELD = "GET_PRODUCT_SEARCH_FIELD";//Action type này sẽ được sử dụng để lấy sản phẩm theo trường từ API.
export const GET_PRODUCT_FILTER_PRICE = "GET_PRODUCT_FILTER_PRICE";//Action type này sẽ được sử dụng để lấy sản phẩm theo giá từ API.
export const GET_REVIEW = "GET_REVIEW";//Action type này sẽ được sử dụng để lấy tất cả đánh giá từ API.
export const TOGGLE_CART = "TOGGLE_CART";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn giỏ hàng.
export const GET_CART = 'GET_CART';//Action type này sẽ được sử dụng để lấy giỏ hàng từ API.
export const ADD_CART = "ADD_CART";//Action type này sẽ được sử dụng để thêm sản phẩm vào giỏ hàng.
export const IS_LOADING_CART = 'IS_LOADING_CART';//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy giỏ hàng từ API.
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';//Action type này sẽ được sử dụng để xóa sản phẩm trong giỏ hàng.
export const AMOUNT_CART = "AMOUNT_CART";//Action type này sẽ được sử dụng để cập nhật số lượng sản phẩm trong giỏ hàng.
export const RESET_CART = "RESET_CART";//Action type này sẽ được sử dụng để reset giỏ hàng.
export const UPDATE_ONE_CART = "UPDATE_ONE_CART";//Action type này sẽ được sử dụng để cập nhật giỏ hàng.
export const IS_LOADING_PC = "IS_LOADING_PC";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi lấy sản phẩm theo trang từ API.
export const SET_SUB_TOTAL_CART = "SET_SUB_TOTAL_CART";//Action type này sẽ được sử dụng để cập nhật tổng tiền trong giỏ hàng.
export const GET_PRODUCT_RELATED = "GET_PRODUCT_RELATED";//Action type này sẽ được sử dụng để lấy sản phẩm liên quan từ API.
export const GET_PRODUCT_ALSO_LIKE = "GET_PRODUCT_ALSO_LIKE";//Action type này sẽ được sử dụng để lấy sản phẩm cũng có thể bạn thích từ API.
export const IS_LOADING_AUTH = "IS_LOADING_AUTH";//Action type này sẽ được sử dụng để hiển thị hoặc ẩn loading khi đăng nhập.
export const PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"//Action type này sẽ được sử dụng để hiển thị thông báo khi không tìm thấy sản phẩm.
export const DELETE_CMT = "DELETE_CMT";//Action type này sẽ được sử dụng để xóa bình luận.
export const ON_RESET_POSTS = "ON_RESET_POSTS";//Action type này sẽ được sử dụng để reset bài viết.